# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
  co: pr checkout

  # Fork a repo into my own ownership, and set the default (so the delete in unfork will work).
  fork: |
    !f() {
      gh repo fork --remote;
      gh repo set-default $(git remote -v | sed -n -E -e '/origin/s@.*github.com/(.*)\.git .*@\1@p');
    }; f

  # Remove a fork, and restore the remotes to as they were.
  unfork: |
    !f() {
      gh repo delete;
      git remote remove origin;
      git remote rename upstream origin;
    }; f
